FROM python:3.9-slim

WORKDIR /app

# Install netcat for the health check
RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat-traditional && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.consumer.txt .
RUN pip install --no-cache-dir -r requirements.consumer.txt

# Copy application files
COPY weather_consumer.py .

# Run the Python script directly
CMD ["python", "weather_consumer.py"]
