global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: /metrics

  - job_name: 'hadoop-namenode'
    static_configs:
      - targets: ['namenode:9870']
    metrics_path: /metrics

  - job_name: 'hadoop-datanode'
    static_configs:
      - targets: ['datanode:9864']
    metrics_path: /metrics

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: /metrics
    scheme: http
    authorization:
      type: Bearer
      credentials: 'my-token'